### ISSUE TITLE
cargo and passengers overlaps train at station

### ISSUE THREAD

**Issue by NSTrains** [OpenLoco/OpenLoco#1601] opened 2022-08-14 19:07 UTC
**Version information:**
 - Platform: Windows 10
 - Version: 22.06.1
 - Build/commit: adb6f6c

**Describe the bug**
whenever a train is at a station, cargo and passengers will be overlapping and cutting off part of the trains.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any scenario or save game
2. find any station that has cargo or passenger and a train
3. you will see that the cargo or passengers will be overlapping the train

**Expected behaviour**
the cargo and passengers will be behind the train

**Screenshots**
https://cdn.discordapp.com/attachments/701513891821387836/1008086444105023619/overlap.PNG

**Additional context**
this may or may not be a duplicate to another issue

**Comment by AaronVanGeffen** [comment] 2022-08-14 19:14
Duplicate of #1483

**Closed** 2022-08-14 19:15 UTC
Labels: duplicate
