### ISSUE TITLE
Crash on Startup on Linux

### ISSUE THREAD

**Issue by d10sfan** [OpenLoco/OpenLoco#1922] opened 2023-04-20 18:32 UTC
**Version information:**
 - Platform: Linux
 - Version: 23.03 & master
 - Build/commit: [9e5cdcc](https://github.com/OpenLoco/OpenLoco/commit/9e5cdcc2edac8f6c4c6761feffff7851b9438df9)

**Describe the bug**

After building the game and attempting to run the OpenLoco binary, the game immediately crashes.

**To Reproduce**
Steps to reproduce the behaviour:
1. Build the game on Linux, either on debug or release mode
2. Put the binary in the steam directory that contains the Locomotion game files, along with the data directory
3. Attempt to run the game
4. Game crashes

**Expected behaviour**
Game not to crash

**Screenshots**
N/A

**Additional context**

I see the following stack trace when it crashes (from the 9e5cdcc commit in debug mode):

```
0xf770541f in std::basic_istream<char, std::char_traits<char> >::seekg (this=0xffffbdc0, __off=0, __dir=std::_S_end)
    at /usr/src/debug/gcc/gcc-build/x86_64-pc-linux-gnu/32/libstdc++-v3/include/bits/istream.tcc:920
Downloading source file /usr/src/debug/gcc/gcc-build/x86_64-pc-linux-gnu/32/libstdc++-v3/include/bits/istream.tcc
920     /usr/src/debug/gcc/gcc-build/x86_64-pc-linux-gnu/32/libstdc++-v3/include/bits/istream.tcc: Directory not empty.                    
(gdb) bt
#0  0xf770541f in std::basic_istream<char, std::char_traits<char> >::seekg (this=0xffffbdc0, __off=0, __dir=std::_S_end)
    at /usr/src/debug/gcc/gcc-build/x86_64-pc-linux-gnu/32/libstdc++-v3/include/bits/istream.tcc:920
#1  0x01173853 in OpenLoco::FileStream::getLength (this=0xffffbdbc)
    at /__w/packages/packages/engines/openloco/source/src/Utility/include/OpenLoco/Utility/Stream.hpp:245
#2  0x01259f02 in OpenLoco::SawyerStreamReader::validateChecksum (this=0xffffbc84)
    at /__w/packages/packages/engines/openloco/source/src/OpenLoco/src/S5/SawyerStream.cpp:176
#3  0x01254c5b in OpenLoco::S5::importSave (stream=...) at /__w/packages/packages/engines/openloco/source/src/OpenLoco/src/S5/S5.cpp:404
#4  0x0125561f in OpenLoco::S5::importSaveToGameState (stream=..., flags=OpenLoco::S5::LoadFlags::titleSequence)
    at /__w/packages/packages/engines/openloco/source/src/OpenLoco/src/S5/S5.cpp:555
#5  0x0125554e in OpenLoco::S5::importSaveToGameState (path=..., flags=OpenLoco::S5::LoadFlags::titleSequence)
    at /__w/packages/packages/engines/openloco/source/src/OpenLoco/src/S5/S5.cpp:540
#6  0x012603fe in OpenLoco::Title::loadTitle () at /__w/packages/packages/engines/openloco/source/src/OpenLoco/src/Title.cpp:127
#7  0x01260b59 in operator() (__closure=0x0) at /__w/packages/packages/engines/openloco/source/src/OpenLoco/src/Title.cpp:281
#8  0x01260b73 in _FUN () at /__w/packages/packages/engines/openloco/source/src/OpenLoco/src/Title.cpp:283
#9  0xf7e6a5d5 in ?? ()
```

Let me know if there's any other details that can help. Thanks!

For reference, this is the build script I'm building: https://github.com/luxtorpeda-dev/packages/blob/1f7fe3a1368dcfc00bc6317bfc550957972f0c27/engines/openloco/build.sh

**Comment by duncanspumpkin** [comment] 2023-05-10 19:27
I see you closed this issue was that just because luxtorpeda is not going to have openloco?

**Comment by duncanspumpkin** [comment] 2023-05-11 05:26
I started looking at it last night. I'll try add a few diagnostics and maybe get you to run a test branch.

**Comment by duncanspumpkin** [comment] 2023-05-11 08:09
Could you try out https://github.com/duncanspumpkin/OpenLoco/tree/sawyerstream . I noticed a potential issue where we use a write function on a stream open for reading. That might be the cause of the issue.

**Comment by d10sfan** [comment] 2023-05-11 19:20
Thanks, I'll try that when I have a chance and let you know.

**Comment by d10sfan** [comment] 2023-05-11 19:45
I tried that change and got the following:


```
Thread 1 "openloco" received signal SIGSEGV, Segmentation fault.
0xf77120bf in std::basic_istream<char, std::char_traits<char> >::seekg (this=0xffffcdb0, __off=0, __dir=std::_S_end)
    at /usr/src/debug/gcc/gcc-build/x86_64-pc-linux-gnu/32/libstdc++-v3/include/bits/istream.tcc:935
Downloading source file /usr/src/debug/gcc/gcc-build/x86_64-pc-linux-gnu/32/libstdc++-v3/include/bits/istream.tcc
935     /usr/src/debug/gcc/gcc-build/x86_64-pc-linux-gnu/32/libstdc++-v3/include/bits/istream.tcc: Directory not empty.                                      
(gdb) bt
#0  0xf77120bf in std::basic_istream<char, std::char_traits<char> >::seekg (this=0xffffcdb0, __off=0, __dir=std::_S_end)
    at /usr/src/debug/gcc/gcc-build/x86_64-pc-linux-gnu/32/libstdc++-v3/include/bits/istream.tcc:935
#1  0x01173933 in OpenLoco::FileStream::getLength (this=0xffffcdac)
    at /__w/packages/packages/engines/openloco/source/src/Utility/include/OpenLoco/Utility/Stream.hpp:244
#2  0x01262499 in OpenLoco::SawyerStreamReader::validateChecksum (this=0xffffcc78)
    at /__w/packages/packages/engines/openloco/source/src/OpenLoco/src/S5/SawyerStream.cpp:170
#3  0x0125cbf7 in OpenLoco::S5::importSave (stream=...) at /__w/packages/packages/engines/openloco/source/src/OpenLoco/src/S5/S5.cpp:407
#4  0x0125d5cf in OpenLoco::S5::importSaveToGameState (stream=..., flags=OpenLoco::S5::LoadFlags::titleSequence)
    at /__w/packages/packages/engines/openloco/source/src/OpenLoco/src/S5/S5.cpp:568
#5  0x0125d4fe in OpenLoco::S5::importSaveToGameState (path=..., flags=OpenLoco::S5::LoadFlags::titleSequence)
    at /__w/packages/packages/engines/openloco/source/src/OpenLoco/src/S5/S5.cpp:553
#6  0x01268938 in OpenLoco::Title::loadTitle () at /__w/packages/packages/engines/openloco/source/src/OpenLoco/src/Title.cpp:127
#7  0x01269093 in operator() (__closure=0x0) at /__w/packages/packages/engines/openloco/source/src/OpenLoco/src/Title.cpp:281
#8  0x012690ad in _FUN () at /__w/packages/packages/engines/openloco/source/src/OpenLoco/src/Title.cpp:283
#9  0xf7e6a5d5 in ?? ()
```

**Comment by duncanspumpkin** [comment] 2023-05-11 19:50
Okay. Looks like I'll have to go the masses of printf debugging route. Was hoping it was just that little mistake.

**Comment by duncanspumpkin** [comment] 2023-05-12 07:26
I've added a few logging functions and additional errors. Could you try again on the updated branch.

**Comment by d10sfan** [comment] 2023-05-15 14:32
Ok, this is what I get from the latest:

```
OpenLoco, v22.03.1-517 (6b59a676 on HEAD, DEBUG)                                                                                                             
Address 0x00497ffc straddles page boundary (page0 = 0x00497000, page1 = 0x00498000), injecting 4 nops
Downloading separate debug info for /run/media/d10sfan/Storage/SteamLibrary/steamapps/common/SteamLinuxRuntime_sniper/var/tmp-SX2041/lib/i386-linux-gnu/libjack.so.0
[New Thread 0xf6a81b40 (LWP 87354)]                                                                                                                          
[Thread 0xf6a81b40 (LWP 87354) exited]
[New Thread 0xf53ffb40 (LWP 87355)]
[Thread 0xf53ffb40 (LWP 87355) exited]
[New Thread 0xf53ffb40 (LWP 87356)]
[Thread 0xf53ffb40 (LWP 87356) exited]
[New Thread 0xf53ffb40 (LWP 87357)]
[New Thread 0xf0bfeb40 (LWP 87358)]
[New Thread 0xeffdcb40 (LWP 87359)]
Create progress bar
SendMessage(PBM_SETRANGE, 256)
SendMessage(PBM_SETSTEP, 1)
SendMessage(PBM_SETPOS, 30)
OpenMutexA(0x1f0001, false, Locomotion_GSKMUTEX)
CreateMutexA(0x0, false, Locomotion_GSKMUTEX)
SendMessage(PBM_SETPOS, 40)
Destroy progress bar
Create progress bar
SendMessage(PBM_SETRANGE, 256)
SendMessage(PBM_SETSTEP, 1)
SendMessage(PBM_SETPOS, 60)
G1 element count doesn't match expected value:
Expected 4122; Got 3896
Got Steam G1.DAT variant, will fix elements automatically.
SendMessage(PBM_SETPOS, 220)
SendMessage(PBM_SETPOS, 235)
SendMessage(PBM_SETPOS, 250)
Destroy progress bar
Importing Save to Game State: Data/title.dat
Stream Pos 0

Thread 1 "openloco" received signal SIGSEGV, Segmentation fault.
0xf77120bf in std::basic_istream<char, std::char_traits<char> >::seekg (this=0xffffbd90, __off=0, __dir=std::_S_end)
    at /usr/src/debug/gcc/gcc-build/x86_64-pc-linux-gnu/32/libstdc++-v3/include/bits/istream.tcc:935
Downloading source file /usr/src/debug/gcc/gcc-build/x86_64-pc-linux-gnu/32/libstdc++-v3/include/bits/istream.tcc
935     /usr/src/debug/gcc/gcc-build/x86_64-pc-linux-gnu/32/libstdc++-v3/include/bits/istream.tcc: Directory not empty.                                      
(gdb) bt
#0  0xf77120bf in std::basic_istream<char, std::char_traits<char> >::seekg (this=0xffffbd90, __off=0, __dir=std::_S_end)
    at /usr/src/debug/gcc/gcc-build/x86_64-pc-linux-gnu/32/libstdc++-v3/include/bits/istream.tcc:935
#1  0x011739e0 in OpenLoco::FileStream::getLength (this=0xffffbd8c)
    at /__w/packages/packages/engines/openloco/source/src/Utility/include/OpenLoco/Utility/Stream.hpp:252
#2  0x01262613 in OpenLoco::SawyerStreamReader::validateChecksum (this=0xffffbc58)
    at /__w/packages/packages/engines/openloco/source/src/OpenLoco/src/S5/SawyerStream.cpp:173
#3  0x0125ccdd in OpenLoco::S5::importSave (stream=...) at /__w/packages/packages/engines/openloco/source/src/OpenLoco/src/S5/S5.cpp:409
#4  0x0125d719 in OpenLoco::S5::importSaveToGameState (stream=..., flags=OpenLoco::S5::LoadFlags::titleSequence)
    at /__w/packages/packages/engines/openloco/source/src/OpenLoco/src/S5/S5.cpp:571
#5  0x0125d635 in OpenLoco::S5::importSaveToGameState (path=..., flags=OpenLoco::S5::LoadFlags::titleSequence)
    at /__w/packages/packages/engines/openloco/source/src/OpenLoco/src/S5/S5.cpp:556
#6  0x01268c2a in OpenLoco::Title::loadTitle () at /__w/packages/packages/engines/openloco/source/src/OpenLoco/src/Title.cpp:127
#7  0x01269385 in operator() (__closure=0x0) at /__w/packages/packages/engines/openloco/source/src/OpenLoco/src/Title.cpp:281
#8  0x0126939f in _FUN () at /__w/packages/packages/engines/openloco/source/src/OpenLoco/src/Title.cpp:283
#9  0xf7e6a5d5 in ?? ()
```

**Comment by d10sfan** [comment] 2023-06-04 01:53
Anything more needed on this? Thanks!

**Comment by AaronVanGeffen** [comment] 2023-06-04 08:01
@janisozaur Do you perhaps have any ideas as to what might be causing this?

**Comment by duncanspumpkin** [comment] 2023-06-09 11:39
Could you try https://github.com/OpenLoco/OpenLoco/pull/1979 its a general cleanup of the streams so might shake something loose.

**Comment by d10sfan** [comment] 2023-06-09 18:47
I am still getting a crash with this

```
Thread 1 "openloco" received signal SIGSEGV, Segmentation fault.
0xf77120bf in std::basic_istream<char, std::char_traits<char> >::seekg (this=0xffffbca4, __off=0, __dir=std::_S_end)
    at /usr/src/debug/gcc/gcc-build/x86_64-pc-linux-gnu/32/libstdc++-v3/include/bits/istream.tcc:935
Downloading source file /usr/src/debug/gcc/gcc-build/x86_64-pc-linux-gnu/32/libstdc++-v3/include/bits/istream.tcc
935     /usr/src/debug/gcc/gcc-build/x86_64-pc-linux-gnu/32/libstdc++-v3/include/bits/istream.tcc: Directory not empty.                      
(gdb) bt
#0  0xf77120bf in std::basic_istream<char, std::char_traits<char> >::seekg (this=0xffffbca4, __off=0, __dir=std::_S_end)
    at /usr/src/debug/gcc/gcc-build/x86_64-pc-linux-gnu/32/libstdc++-v3/include/bits/istream.tcc:935
#1  0x0135f8ee in OpenLoco::getFileLength (fs=...) at /__w/packages/packages/engines/openloco/source/src/Core/src/FileStream.cpp:10
#2  0x0135fba7 in OpenLoco::FileStream::open (this=0xffffbca0, path=..., mode=OpenLoco::StreamMode::read)
    at /__w/packages/packages/engines/openloco/source/src/Core/src/FileStream.cpp:51
#3  0x0135f99b in OpenLoco::FileStream::FileStream (this=0xffffbca0, path=..., mode=OpenLoco::StreamMode::read)
    at /__w/packages/packages/engines/openloco/source/src/Core/src/FileStream.cpp:18
#4  0x0126574e in OpenLoco::S5::importSaveToGameState (path=..., flags=OpenLoco::S5::LoadFlags::titleSequence)
    at /__w/packages/packages/engines/openloco/source/src/OpenLoco/src/S5/S5.cpp:554
#5  0x01270c5c in OpenLoco::Title::loadTitle () at /__w/packages/packages/engines/openloco/source/src/OpenLoco/src/Title.cpp:127
#6  0x012713b7 in operator() (__closure=0x0) at /__w/packages/packages/engines/openloco/source/src/OpenLoco/src/Title.cpp:281
#7  0x012713d1 in _FUN () at /__w/packages/packages/engines/openloco/source/src/OpenLoco/src/Title.cpp:283
#8  0xf7e6a661 in ?? ()
```

**Closed** 2023-11-17 21:47 UTC
Labels: bug, investigate

**Comment by janisozaur** [comment] 2023-11-17 22:36
Is it fixed now?
