### ISSUE TITLE
ios_base::failbit set: iostream stream error

### ISSUE THREAD

**Issue by MisterX2000** [OpenLoco/OpenLoco#1178] opened 2021-09-17 12:30 UTC
**Version information:**
 - Platform: Windows 10 21H1
 - Version: 21.09.1
 - Build/commit: e18b716

**Describe the bug**
When I start the game after selecting the original games folder, I get the following error:
`ios_base::failbit set: iostream stream error`

**To Reproduce**
Steps to reproduce the behaviour:
1. Start Game with `openloco.exe`
2. Select Game install path inside Steam directory (.../steamapps/common/Locomotion)

**Comment by AaronVanGeffen** [comment] 2021-09-17 12:45
This is caused by no legacy config file being present. Fixed by #1179.

**Closed** 2021-09-21 17:49 UTC
Labels: bug
