### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Thaodan** [OpenLoco/OpenLoco#386] opened 2019-12-04 21:06 UTC
You said you want to share code between OpenLoco and OpenRCT2 but who could you share GPL code into a MIT license licensed project?

**Comment by LeftofZen** [comment] 2022-02-15 02:27
Can you provide some more information here please? Who is 'you'?
In any case, providing shared code could be done as simply as putting that shared code in a shared repository under a license which allows linking. Almost all major licenses allow this: https://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licences.

**Comment by Thaodan** [comment] 2022-02-15 06:57
> Can you provide some more information here please? Who is 'you'? In any case, providing shared code could be done as 
You as in the readme said.

>In any case, providing shared code could be done as simply as putting that shared code in a shared repository under a license which allows linking

That would require a re license of some code since OpenRCT2 uses GPL.

**Comment by LeftofZen** [comment] 2022-02-15 07:03
True, we'd have to move OpenLoco to GPL or something similar. In any case, I don't think there are concrete plans to do either of these things (relicense, or start using shared lib) so we probably don't need to think about this too much now.

**Comment by duncanspumpkin** [comment] 2022-02-15 07:41
The idea is that the common code would be in [libsawyer](https://github.com/IntelOrca/libsawyer).

**Comment by LeftofZen** [comment] 2022-02-15 07:45
I think the problem is that OpenRCT2 is on GPL and any libraries a GPL project uses must also be GPL

**Comment by Thaodan** [comment] 2022-02-15 08:07
> I think the problem is that OpenRCT2 is on GPL and any libraries a GPL
> project uses must also be GPL
> 

You can upgrade code to GPL but not downgrade to in this direction it works no 
need for every depedency to be GPL.

**Comment by AaronVanGeffen** [comment] 2023-08-10 18:08
No code is being shared directly with OpenRCT2 right now. The idea is that OpenRCT2 might adopt modules of OpenLoco code in the future. The other way around is unlikely for several reasons. I am therefore closing this issue.

**Closed by AaronVanGeffen** 2023-08-10 18:08 UTC
Labels: information, discussion, incomplete
