### ISSUE TITLE
Text input visual cursor position is always at the beginning 

### ISSUE THREAD

**Issue by Lev135** [OpenLoco/OpenLoco#2384] opened 2024-03-31 18:17 UTC
**Version information:**
 - Platform: Windows 10
 - Version: 24.03

**Describe the bug**
In all text inputs visual cursor position is always at the beginning of the line (while letters are added to the end).
This is only 24.03 bug, for 24.02.1 everything is fine.

24.03 (on this screenshot cursor is not clear, but it's at the beginning):
![image](https://github.com/OpenLoco/OpenLoco/assets/35816057/73b4b5bc-d413-457a-ab5d-81451af8d2d9)
24.02.1 (correct behavior):
![image](https://github.com/OpenLoco/OpenLoco/assets/35816057/94a773c1-346d-48bd-bbe7-6c72168973d5)

**Comment by AaronVanGeffen** [comment] 2024-03-31 19:34
Duplicate of #2379. Has been fixed on master, so closing this.

**Closed** 2024-03-31 19:34 UTC
Labels: duplicate
