### ISSUE TITLE
Music volume is not saved on exit

### ISSUE THREAD

**Issue by senner007** [OpenLoco/OpenLoco#859] opened 2021-03-28 13:18 UTC
**Version information:**
 - Platform: Windows 10
 - Version: 21.03

**Describe the bug**
Music volume is not saved on exit

**To Reproduce**
1. Open game
2. Set Music volume slide to 50%
3. Exit game
4. Open game and music volume is at 100%

**Expected behaviour**
Volume should be saved

**Comment by senner007** [comment] 2021-03-28 13:50
I would like to do a pr myself. I normally write ts and C# in vscode, so I just have to set up the VS with dependencies and compile it.

**Comment by AaronVanGeffen** [comment] 2021-03-28 14:54
Duplicate of #729

**Comment by senner007** [comment] 2021-03-28 15:12
Ahh, should have checked previous issues first. Thanks

**Closed** 2021-08-23 14:13 UTC
Labels: duplicate
