### ISSUE TITLE
Weather like in OpenRCT2?

### ISSUE THREAD

**Issue by NSTrains** [OpenLoco/OpenLoco#2096] opened 2023-08-18 17:52 UTC
**Describe the solution you'd like**
Add OpenRCT2 weather into OpenLoco

**Describe alternatives you've considered**
Make new Weather for OpenLoco instead of usinng the code from OpenRCT2

**Comment by AaronVanGeffen** [comment] 2023-08-18 18:23
Duplicate of #131. Unlikely to be implemented, to be honest. It's not going to be a copy/paste job of OpenRCT2 code, anyway.

**Closed** 2023-08-18 18:23 UTC
