### ISSUE TITLE
[BUG] Gridlines disappear after leaving construction mode

### ISSUE THREAD

**Issue by Streckraupp** [OpenLoco/OpenLoco#2467] opened 2024-04-28 21:27 UTC
**Version information:**
 - Platform: Win10
 - Version: v24.04

**Describe the bug**
I activated the option 'show gridlines on landscape'. When I exit construction mode (e.g. tram track construction), the gridlines disappear. I suppose it is because construction mode already has gridlines mode active while the construction mode is open, and once you close it, there is a 'force turn off gridlines' which overwrites the 'show gridlines on landscape' option. 
Closing construction mode actually also turns off all 'view' options (such as underground view), but this part also occur in the original Locomotion, the bug is that the original DOES NOT turn off the option 'show gridlines on landscape' upon closinng any construction mode. As an additional feature (not bugfix, but just using this bug description as a suggestion), the view options could remain active upon closing construction mode.

**To Reproduce**
Steps to reproduce the behaviour:
1. Activate option 'show gridlines on ladnscape'.
2. Open any construction mode (e.g. tram track construction).
3. Close the construction mode.
4. Gridlines disappeared.

**Expected behaviour**
If the option is active, the gridlines shouldn't disappear.

**Comment by AaronVanGeffen** [comment] 2024-04-28 21:42
Duplicate of #2412, fixed by #2413. Will be fixed in the next release! :)

**Closed by AaronVanGeffen** 2024-04-28 21:42 UTC
