### ISSUE TITLE
UTF symbols displayed as ?????

### ISSUE THREAD

**Issue by hhrhhr** [OpenLoco/OpenLoco#580] opened 2020-08-18 09:09 UTC
**OS:**  Windows 10
**Version:**  2004
**Commit/Build:** 1dcc29b

**Steps to reproduce:**
1. Select Russian or Slovak language

**Screenshots / Video:**
![l2](https://user-images.githubusercontent.com/966048/90493985-ae392980-e14b-11ea-8068-fa206cd47bec.png)
![l1](https://user-images.githubusercontent.com/966048/90494004-b3967400-e14b-11ea-9ba4-30ab6c5f4d1d.png)

**Comment by AaronVanGeffen** [comment] 2020-08-18 10:51
Unfortunately, we cannot extend the sprite font at the moment. This is a known issue; I really hope this can be addressed in the short term.

**Comment by AaronVanGeffen** [comment] 2021-02-10 10:16
Closing this as a duplicate of #304

**Closed by AaronVanGeffen** 2021-02-10 10:16 UTC
Labels: bug
