### ISSUE TITLE
"Deselct All" button in object selection

### ISSUE THREAD

**Issue by stelepe** [OpenLoco/OpenLoco#2451] opened 2024-04-17 11:00 UTC
In the object selection window, would it bepossible to implement a button to "deleselct all"? I feel it would be a really useful feature when you don't want vaniila stuff from the buses tab for example.

The button would only affect the tab/submenu of the tab you are in. E.g "Vehicles -> Buses" or "Trees"

**Comment by LeftofZen** [comment] 2024-04-17 11:02
Duplicate of #2450

**Closed by LeftofZen** 2024-04-17 11:02 UTC
Labels: duplicate
