### ISSUE TITLE
Game crashes while trying to build tunnels

### ISSUE THREAD

**Issue by JauneFonce** [OpenLoco/OpenLoco#1783] opened 2023-01-30 02:35 UTC
**Version information:**
 - Platform: Windows 10
 - Version: 23.01
 - Build/commit: ff64c74d

**Describe the bug**
While building tracks or roads to a cliff, when it is supposed to switch to tunnel mode, the game crashes (program not responding).

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Build tracks
2. Click on laying tracks to a cliff

**Expected behaviour**
Switch background to underground view and build tunnels.

**Additional context**
I created a 100% flat landscape scenario. In the Landscape tab, Generator Improved, Sea level +2, Min land height 3, Hill density 0%.

**Comment by JauneFonce** [comment] 2023-03-03 23:28
Still crashes with version 23.02.

**Comment by duncanspumpkin** [comment] 2023-03-06 19:34
I can't reproduce this. Could you provide screenshots showing what you are doing.

**Comment by JauneFonce** [comment] 2023-03-07 01:42
![Step1](https://user-images.githubusercontent.com/123914886/223297314-723b7489-18d0-4457-8bc5-fa6dc6142e13.png)

**Comment by JauneFonce** [comment] 2023-03-07 01:44
![Step2](https://user-images.githubusercontent.com/123914886/223297636-eeb149d6-d6e6-49dc-8185-797cf1ff934b.png)

**Comment by duncanspumpkin** [comment] 2023-03-07 08:16
I tried a few times and I'm not able to recreate the bug. Tried both on 23.01 and the latest HEAD. Is it only happening on this one map? Could you provide the save? Its possible its related to the track type but unlikely. 
![image](https://user-images.githubusercontent.com/1277401/223363439-537e871f-4982-4fa3-aeac-640c66063899.png)

**Comment by JauneFonce** [comment] 2023-03-07 21:26
Hello Duncan,

First of all, I would like to thank you for your time on debugging this case.

You will find attached the save file.

Regards,

Carl

Duncan ***@***.***> a écrit :

**Comment by janisozaur** [comment] 2023-03-08 05:16
There is no arrangement. You have to upload it via GitHub UI

**Comment by JauneFonce** [comment] 2023-03-08 22:22
[Save.zip](https://github.com/OpenLoco/OpenLoco/files/10925712/Save.zip)

**Comment by duncanspumpkin** [comment] 2023-03-09 08:27
Okay can confirm it crashes inside vanilla function 0x0046457C. Which is a paint function. Crashing when trying to access the tunnel image. Seems it has an invalid tunnel reference.

**Comment by duncanspumpkin** [comment] 2023-03-09 08:37
Found the mistake. Will be fixed in the next release.

**Closed** 2023-03-09 09:46 UTC
Labels: investigate
