### ISSUE TITLE
Game crashes on start on 22.06 but not previous versions

### ISSUE THREAD

**Issue by eldomtom2** [OpenLoco/OpenLoco#1554] opened 2022-07-01 16:43 UTC
**Version information:**
 - Platform: Windows 7
 - Version 22.06

The game now crashes on start for me. This only occurs on 22.06 and not any of the previous versions I have downloaded. I have attached the crash dump
[3f9615c1-1ea7-4690-bae6-c74dda4330f5(OpenLoco, v22.06 (5eac98c on master)).dmp.zip](https://github.com/OpenLoco/OpenLoco/files/9030445/3f9615c1-1ea7-4690-bae6-c74dda4330f5.OpenLoco.v22.06.5eac98c.on.master.dmp.zip)
.

**Comment by duncanspumpkin** [comment] 2022-07-01 16:50
Yes sorry known issue caused by the optimiser. Fix for it already merged. We will issue a .1 release later today.

**Comment by duncanspumpkin** [comment] 2022-07-01 16:52
Ql

**Closed by duncanspumpkin** 2022-07-01 16:52 UTC
