### ISSUE TITLE
multiplayer I.S.P

### ISSUE THREAD

**Issue by killer90k2** [OpenLoco/OpenLoco#1292] opened 2022-01-15 10:35 UTC
please include multiplayer for us to play the game with others 1v1 or co op would be great thanks used to play this with my dad now we are trying to play again and cant thanks

**Comment by AaronVanGeffen** [comment] 2022-01-17 12:45
Duplicate of #95. Unfortunately not trivial to add, but definitely something we'd like to do in the future.

**Closed by AaronVanGeffen** 2022-01-17 12:45 UTC
Labels: duplicate
