### ISSUE TITLE
Leap Year 😄 

### ISSUE THREAD

**Issue by FenderBender2** [OpenLoco/OpenLoco#2458] opened 2024-04-22 16:34 UTC
**Version information:**
 - Platform: Windows 10
 - Version: 24.04
 - Build/commit: [e.g. f08479f]

**Describe the bug**
There is no leap year in 1900, except in Locomotion 😄. This is carried over from the vanilla version.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start at year 1900.
2. Wait until the 29th February.

**Screenshots**
![image](https://github.com/OpenLoco/OpenLoco/assets/121941598/224ccb54-7388-4412-87c5-10220947f5bd)

**Comment by AaronVanGeffen** [comment] 2024-04-22 16:45
Duplicate of #1671 ;)

**Closed** 2024-04-22 16:46 UTC
Labels: duplicate
