### ISSUE TITLE
Load Game dialog is sometimes blank

### ISSUE THREAD

**Issue by FenderBender2** [OpenLoco/OpenLoco#2255] opened 2024-01-16 22:11 UTC
**Version information:**
 - Platform: Windows 10
 - Version: v24.01
 - Build/commit: 39f4765e on master

**Describe the bug**
Load Game window show no files or folders, even when there are some available in the current folder.

**To Reproduce**
Steps to reproduce the behaviour:

1. Click on the Load Saved Game icon.
2. Navigate to a folder somewhere on your system. (Vanilla save game files used to be held in C:\Users\<user>\AppData\Local\VirtualStore\Program Files (x86)\Atari\Locomotion\Single Player Saved Games).
3. Clicking on VirtualStore in the path produces a blank file/folder list.
4. Sometimes, when reversing back up the path, the files/folder window stays blank even when navigating back to C:\.

**Expected behaviour**
Files/folders should be displayed.

**Screenshots**
![image](https://github.com/OpenLoco/OpenLoco/assets/121941598/b5575fc9-11d5-4195-8ced-c5fd46d7ec2d)

**Additional context**
Is this anything to do with folders or files that have spaces, or characters such as (x86)?

**Comment by AaronVanGeffen** [comment] 2024-01-16 22:12
Duplicate of #2252. There will likely be a v24.01.1 release to deal with this tomorrow.

**Comment by FenderBender2** [comment] 2024-01-16 22:12
Missed that, sorry.

**Comment by AaronVanGeffen** [comment] 2024-01-16 22:13
Hmm, honestly, I'm not sure what's going wrong. But it'd be better not to go through the VirtualStore stuff, anyway. Is it not an option to use OpenLoco's save folder?

**Comment by FenderBender2** [comment] 2024-01-16 22:15
Yes, but when I had the issue I tested it on the VirtualStore to produce the screen shot.

**Comment by FenderBender2** [comment] 2024-01-16 22:23
I've just done a quick check, and it seems this started happening from 23.07 onwards.

**Comment by duncanspumpkin** [comment] 2024-02-15 21:29
Oh lol this is a funny one its the scroll bar that is broken and its hiding everything because it thinks that it can't be shown. If you click on the scroll bar it should be visible.

**Comment by FenderBender2** [comment] 2024-02-15 21:36
So it is :)

**Closed as completed** 2024-02-16 20:31 UTC
Labels: bug-openloco
