### ISSUE TITLE
Improve exception handling

### ISSUE THREAD

**Issue by AaronVanGeffen** [OpenLoco/OpenLoco#1003] opened 2021-06-16 15:39 UTC
Currently, all (otherwise unhandled) exceptions are caught in OpenLoco.cpp:
https://github.com/OpenLoco/OpenLoco/blob/a15e1421f1a85feb89e82f411a9d94444b91e8fb/src/OpenLoco/OpenLoco.cpp#L1182-L1185

While this reveals the error in stdout, it is lost when the console is closed along with the game. The unfortunate consequence of this is that most players will not see the error message, and instead just observe a crash to desktop.

We should refactor this to use a platform function to display the error in a message box to the user.

**Comment by TransshipmentEnvoy** [comment] 2021-06-17 05:17
Is it a duplicate of #823?

**Closed** 2021-06-17 07:01 UTC
Labels: duplicate, good first issue
