### ISSUE TITLE
The train has to leave in the order of waiting

### ISSUE THREAD

**Issue by locomotion00** [OpenLoco/OpenLoco#2616] opened 2024-09-04 13:45 UTC
The train has to leave in the order of waiting
There are definitely trains that come first or wait at the station, but they often leave randomly

**Comment by LeftofZen** [comment] 2024-09-04 13:47
Thanks for the suggestion. I think this is a duplicate of #2195, would you agree?

**Closed** 2024-09-04 15:17 UTC
