### ISSUE TITLE
Crash on month end

### ISSUE THREAD

**Issue by Pokemanic33** [OpenLoco/OpenLoco#1653] opened 2022-09-24 18:31 UTC
**Version information:**
 - Platform: Windows 10
 - Version: 22.09 (via launcher)
 - Build/commit: 00b883a

**Describe the bug**
Sometimes at the end of any given month, the game crashes. This occurs before the error handler catches it, resulting in no error dialogue and no memory dump (unless made manually via Task Manager).

**To Reproduce**
Steps to reproduce the behaviour:
1. Start or load a scenario
2. Wait until the end of the month

**Expected behaviour**
The game continues without crashing.

**Additional context**
- I have yet to notice pattern or trigger for this crash, so replicating is difficult.
- There seems to be a way to "fix" the problem on a per-boot basis; again, I find it hard to determine if this is truly a pattern, but it seems that launching the game from command line causes the game to stop crashing until the PC is rebooted.
- I made a memory dump via Task Manager, but I did so after OpenLoco froze so I don't know if it will be of use. It is too large to attach directly, so [I've uploaded it to Google Drive instead.](https://drive.google.com/file/d/120UiUDopKUr_6AAn596o2JnFcHWGMKj4/view?usp=sharing) I'm not sure why it's so much larger than the dumps OpenLoco makes itself.

**Comment by duncanspumpkin** [comment] 2022-09-25 06:55
It is larger as it will be a full memory dump rather than a specific to openloco dump.

**Comment by AaronVanGeffen** [comment] 2023-08-10 21:03
Closing this as we're unable to reproduce the issue. If you manage to reproduce the problem, could you file a new issue including the dump file OpenLoco generates when a crash occurs? Thanks.

**Closed by AaronVanGeffen** 2023-08-10 21:03 UTC
Labels: investigate
