### ISSUE TITLE
Game hangs when Ticker elapses while editing Route

### ISSUE THREAD

**Issue by CodingKoopa** [OpenLoco/OpenLoco#2387] opened 2024-04-01 07:12 UTC
**Version information:**
 - Platform: Arch Linux, Hyprland
 - Version: 23.12-1
 - Build/commit: [Built from GitHub Release](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=openloco#n16)

**Describe the bug**
On my save, I have been encountering more and more hangs as I progress further. Unlike the usual segfaults, these require a manual SIGKILL to recover from.

It appears that this can occur when the small Ticker in the bottom right corner is triggered, if (and only if) you are currently editing a route.

**To Reproduce**
Steps to reproduce the behaviour:

1. Load my save: [ticker_issue.tar.gz](https://github.com/OpenLoco/OpenLoco/files/14820595/ticker_issue.tar.gz)
    - I tried to make this the essence of the issue - therefore, the ticker will start right away, and you must move quickly to setup the reproduction before the ticker ends.
2. Click on any vehicle's route, either from the world or from the Vehicle menu.
3. After the ticket ends, the game should hang.

**Expected behaviour**
The game shouldn't hang (and, being able to Ctrl+C in this scenario would be useful, but I assume that's out of the question).

**Screenshots**
See [this video](https://youtu.be/SzbL4TnDiF4) where I reproduce the issue a few times. I have more than just this, but the other setups are more complicated.

**Comment by AaronVanGeffen** [comment] 2024-04-01 08:02
Thanks for the report. I notice you've declared quite an old version, v23.12. This is last December's version; we're at v24.03 now.

Could you check if the problem is resolved in the latest version?

**Comment by duncanspumpkin** [comment] 2024-04-04 07:42
Argh its the damn display frames again. I know the reason will have a fix shortly.

**Comment by duncanspumpkin** [comment] 2024-04-04 07:50
@CodingKoopa if you want to try out https://github.com/OpenLoco/OpenLoco/pull/2397 that should fix it. I tested your save with it. Turns out it doens't have anything to do with the ticker its the ai just happen to add an order during the duration of the ticker which triggers the bug.

**Closed as completed** 2024-04-06 19:12 UTC
Labels: investigate
