### ISSUE TITLE
Crash from netural company being happy it started my bus but only if I can't pay back my loans

### ISSUE THREAD

**Issue by LeeSpork** [OpenLoco/OpenLoco#2722] opened 2024-11-12 11:13 UTC
**Version information:**
 - Platform: Windows 10
 - Version: 24.10
 - Build/commit: 52acc01f

**Describe the bug**
Very specific and esoteric crash that can happen after losing the game from bankruptcy. Reproducing it in debug mode reveals it to be an access violation crash in Company.cpp's `companyEmotionEvent` function.

**To Reproduce**
**Method 2**
1. Start a new game. Method may be more consistent in scenarios with not much going on and no AI companies, such as: [Scenario.zip](https://github.com/user-attachments/files/17723721/Scenario.zip)
2. Buy a bus and have it be running.
3. Go bankrupt (e.g. increase your loan and waste it all on terraforming)
4. Wait about a month. The game should crash.

Video example of method 2: https://youtu.be/0Kk61ayWOBo (sorry for double audio)

**Method 1**
1. Load this save file: [save file.zip](https://github.com/user-attachments/files/17715078/save.file.zip)
2. Open financial window and attempt to decrease loan (and fail due to not having enough balance) at least **twice** (apparently?!)
    - Or get lucky (?)
3. Use extra fast forward to save time. Game will crash specifically on **20 July**.

This consistently made the game crash in my testing.

**Screenshots**
![Image](https://github.com/user-attachments/assets/98583b79-c7cb-4905-a4b9-ba2b7283613a)

**Additional context**
The player company has one vehicle in this save: a bus, which was stopped when the company went bankrupt. If you load the save and are lucky enough for it to not crash, you can see the bus is automatically started on July 20, for whatever reason. Crash appears to be the game trying to make the company with ID 15 happy for the bus starting.

**Comment by AaronVanGeffen** [comment] 2024-11-12 11:51
I imagine this was the same problem @LeftofZen meant to fix with #2673. We haven't merged that PR, though, as it might _hide_ the bug rather than fixing it.

**Comment by LeftofZen** [comment] 2024-11-12 13:53
> I imagine this was the same problem [@LeftofZen](https://github.com/LeftofZen) meant to fix with [#2673](https://github.com/OpenLoco/OpenLoco/pull/2673). We haven't merged that PR, though, as it might _hide_ the bug rather than fixing it.

Yeah that's the same bug, I wasn't able to reproduce it at the time but it looks like we have a repro now

**Comment by LeeSpork** [comment] 2024-11-12 14:22
- When the save is run in the original Locomotion (Steam), the bus does not start itself and the game does not crash.
- The bus is restarted due to some timeout in VehicleHead::updateDaily(). Why?? Surely it shouldn't be doing that, when it was stopped by the company going bankrupt.
- The company that it is trying to make happy is `_updatingCompanyId`, which seems to have not been set in the process leading up to the crash, and thus can be an invalid company.

**Comment by duncanspumpkin** [comment] 2024-11-12 22:12
> * When the save is run in the original Locomotion (Steam), the bus does not start itself and the game does not crash.
> * The bus is restarted due to some timeout in VehicleHead::updateDaily(). Why?? Surely it shouldn't be doing that, when it was stopped by the company going bankrupt.
> * The company that it is trying to make happy is `_updatingCompanyId`, which seems to have not been set in the process leading up to the crash (and thus can be an invalid company; hence the access violation altering me to the issue).

Could you confirm that in vanilla (steam) that when you start the scenario in vanilla and go bankrupt the bus isn't sold? I'm not 100% sure if that is the same as what you are saying.

**Comment by duncanspumpkin** [comment] 2024-11-12 22:24
Looking at the assembly there are a few little mistakes in `vehicleChangeRunningMode` that might be causing this.

**Comment by duncanspumpkin** [comment] 2024-11-12 22:56
Okay found the source of the issues there is a check for bankrupt companies but the check result is being ignored due to a mistake.

**Comment by LeeSpork** [comment] 2024-11-12 23:01
> Could you confirm that in vanilla (steam) that when you start the scenario in vanilla and go bankrupt the bus isn't sold? I'm not 100% sure if that is the same as what you are saying.

I created a new scenario in the original game instead of using my OpenLoco scenario, and confirmed that the bus isn't sold in original Locomotion (Steam) https://youtu.be/6UVjv0pManU&t=9m40s

And OpenLoco crashes when loading the same scenario and replicating the same steps: https://youtu.be/0Kk61ayWOBo&t=2m30s

Files created in original Locomotion in the first video: [Scenario.zip](https://github.com/user-attachments/files/17723721/Scenario.zip) [Saved games.zip](https://github.com/user-attachments/files/17723723/Saved.games.zip)

**Comment by duncanspumpkin** [comment] 2024-11-12 23:05
> > Could you confirm that in vanilla (steam) that when you start the scenario in vanilla and go bankrupt the bus isn't sold? I'm not 100% sure if that is the same as what you are saying.
> 
> I created a new scenario in the original game instead of using my OpenLoco scenario, and confirmed that the bus isn't sold in original Locomotion (Steam) https://youtu.be/6UVjv0pManU&t=9m40s
> 
> And OpenLoco crashes when loading the same scenario and replicating the same steps: https://youtu.be/0Kk61ayWOBo&t=2m30s
> 
> Files created in original Locomotion in the first video: [Scenario.zip](https://github.com/user-attachments/files/17723721/Scenario.zip) [Saved games.zip](https://github.com/user-attachments/files/17723723/Saved.games.zip)

im surprised its not sold

**Comment by LeeSpork** [comment] 2024-11-12 23:26
I also observed #2728. Not sure if its related to whatever this issue is, hence the new issue.

**Closed** 2024-11-14 15:18 UTC
Labels: bug-openloco
