### ISSUE TITLE
Fast forward buttons don't always work

### ISSUE THREAD

**Issue by senner007** [OpenLoco/OpenLoco#799] opened 2021-02-26 21:10 UTC
**Version information:**
 - Platform: [e.g. Windows 10]
 - Version: 21.02

**Comment by AaronVanGeffen** [comment] 2021-02-26 21:27
Could you give a bit more information? I haven't been able to reproduce this myself.

**Comment by senner007** [comment] 2021-02-26 22:30
Can't really say more than that. Sometimes it just doesn't work

**Comment by senner007** [comment] 2021-02-27 07:55
...Meaning nothing happens when clicked

**Comment by AaronVanGeffen** [comment] 2021-02-27 08:14
Any particular windows open when you do? Anything that could help us reproduce the issue it's potentially useful information.

**Comment by AaronVanGeffen** [comment] 2021-02-27 10:56
If this was happening during construction, I think this will have been fixed by #795. It doesn't just affect the paused state, but game speed as well. That would also explain why I can't reproduce it.

**Closed** 2021-03-01 23:29 UTC
