### ISSUE TITLE
Cheat Request: Station size limit

### ISSUE THREAD

**Issue by superchadST345** [OpenLoco/OpenLoco#1648] opened 2022-09-22 00:27 UTC
**Describe the solution you'd like**
I would like a cheat to increase the station size limit to remove "station too large" as well as a separate one to increase station coverage to allow stations that are more spread out.

**Describe alternatives you've considered**
Not aware of any alternatives, this is really a fix for an original bug.

**Additional context**

**Comment by LeftofZen** [comment] 2022-09-22 00:38
We often get this request, so I'm going to close this as duplicate of #358. 

Unfortunately we won't be able to implement this until the game is finished reverse engineering and we have a new save format, which will allow us to increase the existing game limited like station size.

It also isn't a bug, as mentioned it's a limit of the original game.

**Closed** 2022-09-22 00:38 UTC
