### ISSUE TITLE
vehicle list not in order when playing savegames or scenario

### ISSUE THREAD

**Issue by NSTrains** [OpenLoco/OpenLoco#1393] opened 2022-03-20 20:16 UTC
Version information:
 - Windows 10
 - 22.03.1
 - don't know what build/commit it is on.

The vehicle list is not in order that they were invented in the build trains window. For an example, a GP38-2 that was built in 1972 is after a P42DC on the list that was built in 1996. the gp38 should be in between a J Class and a C40-8W

To Reproduce:
Steps to reproduce the behaviour:
1. Go to a savegame or scenario
2. Click on 'build trains'
3. look the list of trains and the year that they were invented
4. you will see that some trains that are invented a year or two that is after another train that was invented a year or two later

Expected behaviour:
The list in the window should be on order the year they were invented.

**Comment by LeftofZen** [comment] 2022-03-20 23:07
I personally haven't seen this error before, but I'm unfamiliar with those trains, they sound like custom objects? I'd bet there is something fishy with either the custom objects or with how the game is handling them. Would you be able to upload the save-game here in a zip file, or send it to me on discord, so I can try to repro the issue? I should have the custom objects lying around somewhere, I'll let you know if I'm missing any.

Also to find out what build/commit it is, look down the bottom-left of your game screen when you're on the main menu: 
![image](https://user-images.githubusercontent.com/7483209/159189890-48d218d2-42e9-4bd8-b213-d7ae1ea10944.png)
The letters+numbers in the parentheses, in my case `a759b81` is the commit hash.

**Comment by NSTrains** [comment] 2022-03-21 15:45
it happens on every save game I have

**Comment by LeftofZen** [comment] 2022-03-21 23:08
I tried to find a scenario where this happens, and it happens in the 'Scotland (BR Set Needed)' scenario, on a couple of vehicles but for example:
![image](https://user-images.githubusercontent.com/7483209/159377555-3eb28b6a-b13a-4982-8d25-7e07d37df503.png)

The class 37 is designed in 1960 and the class 08 designed in 1957

**Comment by LeftofZen** [comment] 2022-03-21 23:23
In vanilla the full list looks like this:
![image](https://user-images.githubusercontent.com/7483209/159378791-1aaab73a-5847-4e89-84ac-7ec5182a249c.png)

In OpenLoco it looks like this (ignore that this list is longer, it's just because OpenLoco lets me have larger game window)
![image](https://user-images.githubusercontent.com/7483209/159378878-b8e34332-f782-47a2-be56-ad0abe528b1e.png)

**Comment by LeftofZen** [comment] 2022-03-21 23:24
In OpenLoco we sort this list here
https://github.com/OpenLoco/OpenLoco/blob/a8f9a7415746c7d5a5403e93d871b3b207a9b39c/src/OpenLoco/Windows/BuildVehicle.cpp#L490-L491

**Comment by AaronVanGeffen** [comment] 2022-03-21 23:37
That snippet suggests the list is effectively sorted by `power` only, not `designed` then `power`.

**Comment by LeftofZen** [comment] 2022-03-21 23:47
That isn't quite true, vanilla DOES sort by `designed` and then by `power`. I've figured it out though, do you want me to tell you the answer or do you want to see for yourself in the PR? :p

**Comment by LeftofZen** [comment] 2022-03-21 23:54
Guess you can look at the PR now haha, but for completeness, the issue is clear in the debugger - once the list is sorted by `designed`, it is correct, but then since `std::sort` isn't stable, it mangles up the ordering when it sorts by `power`, So simply using `std::stable_sort` fixes the issue and the list is now identical to vanilla sorting.

**Comment by duncanspumpkin** [comment] 2022-03-22 07:55
Could you do a quick look at all of our `std::sort` users and check that they are being used correctly.

**Comment by LeftofZen** [comment] 2022-03-23 00:34
> Could you do a quick look at all of our `std::sort` users and check that they are being used correctly.

There are only 4 other users of `std::sort` and none of them have a use case where values are likely to be duplicated (which would require a stable sort). So existing uses look good to me.

**Comment by LeftofZen** [comment] 2022-03-27 10:56
Closed in #1399

**Closed by LeftofZen** 2022-03-27 10:56 UTC
Labels: investigate
