### ISSUE TITLE
In options menu, selected language is blank

### ISSUE THREAD

**Issue by Derpercoaster** [OpenLoco/OpenLoco#2210] opened 2023-12-04 20:15 UTC
**Version information:**
 - Platform: Windows 10
 - Version: 23.11
 - Build/commit: 3f1d349a

**Describe the bug**
The selected language in the options menu always appears blank, regardless of which language is selected.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the options menu
2. Go to the tab with languages
3. Selected language is blank

**Screenshots**
![image](https://github.com/OpenLoco/OpenLoco/assets/60452987/43c5fcb8-28b9-461f-9330-072bb33fe226)

**Comment by AaronVanGeffen** [comment] 2023-12-04 20:36
Presumably fixed by #2207. Could you try a more recent build?

**Comment by Derpercoaster** [comment] 2023-12-04 23:17
23.11 is the most recent release. I don't know how to install the experimental ones.

**Comment by Derpercoaster** [comment] 2023-12-05 07:05
> Presumably fixed by #2207. Could you try a more recent build?

I put the wrong build in by mistake, fixed now.

**Comment by AaronVanGeffen** [comment] 2023-12-07 20:21
I meant a master build, not the latest release build. It is possible to download a master build from GitHub through the Actions tab. Check the bottom of [this page](https://github.com/OpenLoco/OpenLoco/actions/runs/7079079644) for the latest master build artifact. It can be installed like any of our regular release builds.

**Comment by LeftofZen** [comment] 2024-01-01 14:44
23.10 displays correctly for me, 23.11 is first version with broken string

**Comment by AaronVanGeffen** [comment] 2024-01-01 14:50
Oddly enough, it's showing up fine for me on macOS (Wine). This sounds like the bug that was supposed to be tackled by #2207, though.

<img width="591" alt="Screenshot 2024-01-01 at 15 49 03" src="https://github.com/OpenLoco/OpenLoco/assets/604665/2208ca1d-cfd3-4d15-8b0b-7d5714c72fd2">

@duncanspumpkin @ZehMatt, any ideas?

**Comment by LeftofZen** [comment] 2024-01-02 14:14
If you run the game in debug build, an assertion is triggered in SoftwareDrawingContext.cpp around control codes - I assume this is the issue @duncanspumpkin and @ZehMatt (I know you did control code stuff recently). Just open options tab to the region/world in a debug build and it'll hit the assert.

**Comment by duncanspumpkin** [comment] 2024-01-10 17:11
Issue was caused by a change @AaronVanGeffen made. https://github.com/OpenLoco/OpenLoco/pull/2178

**Closed** 2024-01-13 13:34 UTC
Labels: bug
